export 'home.dart';
export 'Amigos/amigos.dart';
export 'Perfil/perfil.dart';
export 'Tienda/tiendaFichas.dart';
export 'Tienda/tiendaTableros.dart';
export 'Estilo/index.dart';
export 'Partidas/partidas.dart';
export 'Partidas/crearPartidas.dart';
export 'Estadisticas/estadisticas.dart';
